### PR TITLE
Needed to control CKAN versioning correctly

### PR DESCRIPTION
**Pull request by Bornholio**
someone check this is right or perhaps we use NetKAN instead.

### CODE REVIEW

**Comment by Bornholio** [comment]
issue #8 closed by this if it works

**Comment by blowfishpro** [comment]
The NetKAN would also have to be updated to look at the .version, right?

**Comment by Olympic1** [comment]
@blowfishpro that is correct.

**Comment by rsparkyc** [comment]
The only thing I would suggest is have the `DOWNLOAD` attribute point to `https://github.com/KSP-RO/RealHeat/releases`.  Also, the indentation seems a bit off, any chance you can auto-format the file?

**Pull request merged**
